export const calendarEvents = [
    {day: 1, message: ""},
    {day: 2, message: ""},
    {day: 3, message: ""},
    {day: 4, message: ""},
    {day: 5, message: ""},
    {day: 6, message: ""},
    {day: 7, message: ""},
    {day: 8, message: ""},
    {day: 9, message: ""},
    {day: 10, message: ""},
    {day: 11, message: ""},
    {day: 12, message: ""},
    {day: 13, message: ""},
    {day: 14, message: ""},
    {day: 15, message: ""},
    {day: 16, message: ""},
    {day: 17, message: ""},
    {day: 18, message: ""},
    {day: 19, message: ""},
    {day: 20, message: ""},
    {day: 21, message: ""},
    {day: 22, message: ""},
    {day: 23, message: ""},
    {day: 24, message: ""},
    
];